# Generated by Django 3.2.8 on 2021-11-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=200)),
                ('Owner', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, default=False, max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True, null=True)),
                ('borrowed', models.BooleanField(default=False)),
                ('pubdate', models.DateTimeField(null=True, verbose_name='date published')),
            ],
        ),
    ]
